name: contactdiff
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - numpy
  - scipy
  - tensorboard
  - pip:
      - omegaconf>=2.3
      - diffusers>=0.11
